config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /#{I18n.available_locales.join("|")}/ do
    resources :subscriptions, only: [:create]
    resources :surveys, only: [:create, :show, :update]
    root "home#index"
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/concerns/categorable.rb
module Categorable
  extend ActiveSupport::Concern

  QUESTION_CATEGORIES = [:coupon_subscription, :other_category]
end

app/models/concerns/validatetable.rb
require 'net/http'
require 'net/https'
module Validatetable
  extend ActiveSupport::Concern

  KEY = ENV['EMAIL_VALIDATION_KEY']
  MIN_QUALITY_SCORE = 0.7

  def validate_mail?(email)
      uri = URI("https://emailvalidation.abstractapi.com/v1/?api_key=#{KEY}&email=#{email}")

      http = Net::HTTP.new(uri.host, uri.port)
      http.use_ssl = true
      http.verify_mode = OpenSSL::SSL::VERIFY_PEER

      request =  Net::HTTP::Get.new(uri)

      response = http.request(request)
      resp = JSON.parse(response.body)

      response.code == '200' && resp['quality_score'].to_f >= MIN_QUALITY_SCORE
  rescue StandardError => error
      puts "Error (#{ error.message })"
  end
end

app/models/question.rb
class Question < ApplicationRecord
  include Categorable
  has_many :survey_answers
  has_many :survey_questions
  validates_presence_of :question_type, :question, :category_type
  accepts_nested_attributes_for :survey_answers, allow_destroy: true

  enum question_type: { single_choice: 0, long_answer: 1 }

  def self.find_cat_type(category)
    Question.where(category_type: "#{category}_questions")
  end
end

app/models/subscription.rb
class Subscription < ApplicationRecord
  include Validatetable
  include Categorable
  has_one :survey
  has_many :questions, through: :survey
  validates :email, presence: true, uniqueness: true
  validates :preferences, presence: true
  validate :email_api_validation, unless: -> { testing? }
  validate :email_format, if: -> { Rails.env.test? }

  PREFERENCES = %w[men women children]
  validates :preferences, inclusion: { in: PREFERENCES, allow_blank: true }


  QUESTION_CATEGORIES.each do |category|
    define_method("create_#{category}_survey") do

      survey || build_survey(category:category).tap(&:save)
    end
  end

  def email_api_validation
    return if validate_mail?(self.email)

    errors.add(:email, I18n.t('activerecord.errors.models.subscription.attributes.email.invalid'))
  end

  def completed_survey?
    survey&.completed
  end

  def testing?
    Rails.env.test?
  end

  def email_format
    return if email =~ URI::MailTo::EMAIL_REGEXP

    errors.add(:email, "is not in a valid format")
  end

end

app/models/survey.rb
class Survey < ApplicationRecord
  include Categorable

  belongs_to :subscription#, foreign_key: 'subscription_id'
  has_many :survey_questions
  has_many :questions, through: :survey_questions
  has_many :survey_answers
  accepts_nested_attributes_for :survey_answers, allow_destroy: true
  after_create_commit :create_questions
  validates_presence_of :category

  def create_questions
    questions = Question.find_cat_type(category)
    question_ids = questions.pluck(:id)

    question_ids.each do |question_id|
      survey_questions.create(question_id: question_id)
    end
  end

  def create_survey_answer_instances
    questions.each { |question| self.survey_answers.build(question_id: question.id) }
  end

end

app/models/survey_answer.rb
class SurveyAnswer < ApplicationRecord
  belongs_to :survey
  belongs_to :question
  validates_presence_of :answer
  before_save :update_lang

  def update_lang
    self.lang = I18n.locale || I18n.default_locale
  end

end

app/models/survey_question.rb
class SurveyQuestion < ApplicationRecord
  belongs_to :survey
  belongs_to :question
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :set_locale

  def turbo_error_message(instance)
    render turbo_stream: turbo_stream.replace('error_message', partial: 'shared/error_message',
                                              locals: { message: instance.errors.full_messages.to_sentence })
  end

  def default_url_options
    { locale: I18n.locale }
  end

  def set_locale
    I18n.locale = extract_locale || I18n.default_locale
  end

  def extract_locale
    parsed_locale = params[:locale]&.to_sym
    I18n.available_locales.include?(parsed_locale) ? parsed_locale : nil
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @subscription = Subscription.new
  end

end

app/controllers/subscriptions_controller.rb
class SubscriptionsController < ApplicationController

  def create
    @subscription = Subscription.new(subscription_params)
    if @subscription.save
      SubscriptionMailer.mailing_subscription(@subscription, request.host_with_port).deliver_later
      render turbo_stream: turbo_stream.replace(
        'subscription_form',
        partial: 'surveys/survey_link',
        locals: { subscription: @subscription })
    else
      turbo_error_message(@subscription)
    end
  end

  private

  def subscription_params
    params.require(:subscription).permit(:email, preferences: [])
  end

end

app/controllers/surveys_controller.rb
class SurveysController < ApplicationController
  before_action :set_survey, only: [:update, :show]
  before_action :create_answer_instances, only: [:show]
  before_action :set_subscription, only: [:create]
  def update
    if @survey.update(survey_params)
        redirect_to survey_path(@survey)
      else
        turbo_error_message(@survey)
    end
  end

  def show

  end

  def create
    @survey = Survey.new(survey_create_params)
    if @survey.save
      redirect_to survey_path(@survey)
    else
      turbo_error_message(@survey)
    end
  end

  private

  def set_survey
    @survey = Survey.find_by(id: params[:id]) || find_subscription_create
  end

  def set_subscription
    subscription = Subscription.find(params[:subscription_id])

    redirect_to survey_path(subscription.survey) if subscription.completed_survey?
  end


  def find_subscription_create
    subscription = Subscription.find(params[:subscription_id])
    subscription.create_coupon_subscription_survey
  end

  def create_answer_instances
    @survey.create_survey_answer_instances
  end

  def survey_create_params
    params.permit(:subscription_id, :category)
  end

  def survey_params
    params.require(:survey).permit(:completed, :subscription_id, :category, survey_answers_attributes: [:answer, :question_id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper

    def locale_links
      links = ""
      current_locale = params[:locale] || I18n.default_locale
      I18n.available_locales.each do |locale|
        if locale.to_s == current_locale.to_s
          links += link_to(locale.to_s.upcase, url_for(locale: locale), class: green_btn_disabled)
        else
          links += link_to(locale.to_s.upcase, url_for(locale: locale), class: green_btn)
        end
      end
      links.html_safe
    end


    def green_btn
      'btn btn-success'
    end

    def green_btn_disabled
      green_btn + ' disabled'
    end

end

app/helpers/subscriptions_helper.rb
module SubscriptionsHelper
  def fashion_preferences(pref)
    t("global.forms.#{pref}").to_sym
  end

  def complete_subscription(survey)
    if survey.completed
      render 'surveys/completed_survey'
    else
      render 'questions/form', survey: survey
    end
  end




end

app/helpers/surveys_helper.rb
module SurveysHelper

  def render_question_form(form)
    t = translation(form)
    numbering = (form.index + 1).to_s
    label_number = "#{numbering}- #{t}"
    question = form.object.question
    question_type = question.question_type

    content_tag(:div, class: "form-group mb-3") do
      concat form.label(label_number, class: "mb-3")
      if question_type == 'long_answer'
        concat form.text_field(:answer, class: "form-control")
      else
        at = alternatives_translation(form)
        concat form.select(:answer, at, {}, class: "form-control")
      end
      concat form.hidden_field(:question_id, value: question.id)
    end
  end

  def translation(form)
    return form.object.question.question if default_language?

    t("questions.#{form.object.question.id}.question")
  end

  def alternatives_translation(form)
    if !default_language? && !number?(form.object.question.alternatives[0])
      t("questions.#{form.object.question.id}.alternatives").split(' ')
    else
      form.object.question.alternatives
    end
  end

  def number?(str)
    Integer(str) rescue false
  end

  def default_language?
    I18n.locale == I18n.default_locale
  end

end

app/views/home/_hero.html.erb
<div class="card bg-dark text-white border-0">
  <%= image_tag('carlos-machado-L1EGIaIY9yk-unsplash.jpg', style: 'height: 50vh;', alt: 'country_side') %>
  <div class="card-img-overlay d-flex align-items-end justify-content-end">
    <div class="card-footer position-absolute bottom-0 end-0">
      <p>Foto de
        <%= link_to('Carlos Machado', 'https://unsplash.com/@kkmachado?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText', class: 'text-decoration-none', target: '_blank') %>
        en
        <%= link_to('Unsplash', "https://unsplash.com/es/fotos/L1EGIaIY9yk?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText", class: 'text-decoration-none', target: '_blank') %>
      </p>
    </div>
  </div>
</div>

app/views/home/_list.html.erb
<div class="col-6">
  <h5><%= t('home_page.index.section') %></h5>
  <ul class="nav flex-column">
    <li><%= t('home_page.index.home') %></li>
    <li><%= t('home_page.index.features') %></li>
    <li><%= t('home_page.index.pricing') %></li>
    <li><%= t('home_page.index.faqs') %></li>
    <li><%= t('home_page.index.about') %></li>
  </ul>
</div>

app/views/home/index.html.erb
<%= render 'home/hero' %>
<div class="container">
  <footer class="mt-4">
    <div class="row">
      <%= render 'home/list' %>
      <div class="col-6">
          <h3><%= t('home_page.index.welcome') %></h3>
          <p><%= t 'home_page.index.services_html' %></p>
          <%= render 'subscriptions/form', subscription: @subscription %>
      </div>
    </div>
  </footer>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Mailing</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render 'shared/language_buttons' %>
    <%= turbo_frame_tag 'error_message' %>
    <div class="mt-4">
      <%= yield %>
    </div>
    <%= render 'shared/footer' %>
  </body>
</html>

app/views/questions/_form.html.erb
  <%= form_with model: survey do |f| %>
    <%= f.fields_for :survey_answers do |form| %>
       <%= render 'questions/survey_answers', form: form %>
    <% end %>

    <%= f.hidden_field :completed, value: true %>
    <%= f.submit t('global.forms.save'), class: green_btn %>
  <% end %>

app/views/questions/_survey_answers.html.erb
<div>
 <%= render_question_form(form) %>
</div>

app/views/shared/_error_message.html.erb
<%= turbo_frame_tag 'error_message' do %>
  <div data-controller="error-message" class="error__message">
    <div class="px-2">
      <%= message %>
    </div>
    <%= link_to 'X','', data: {
      controller: 'error-message',
      action: 'error-message#close_error_message'
    }, class: 'px-3' %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="fixed-bottom">
  <div class="container border-top pt-2 mt-2">
    <div class="row justify-content-center">
      <div class="col-auto">
        <p>&copy; 2023 A footer, Inc. </p>
      </div>
    </div>
  </div>
</div>

app/views/shared/_language_buttons.erb
<div class="btn-group btn-group-toggle">
  <%= locale_links %>
</div>

app/views/shared/_redirect_home.html.erb
<%= link_to t('survey.index.home'), root_path %>

app/views/subscriptions/_form.html.erb
<%= form_with model: subscription, id: 'subscription_form' do |form| %>
  <div class="mb-3">
    <%= form.label :email, t('activerecord.subscription.attributes.user.email'), class: 'form-label' %>
    <%= form.text_field :email, placeholder: t('activerecord.attributes.email_placeholder'), class: 'form-control' %>
  </div>

  <div class="mb-3">
    <%= form.label :preferences, t('models.attributes.preferences') %>
    <% Subscription::PREFERENCES.each do |preference| %>
      <div>
        <%= form.check_box :preferences, { multiple: true }, preference, nil %>
        <%= form.label :preferences, fashion_preferences(preference) %>
      </div>
    <% end %>
  </div>

  <div class="mb-3">
    <%= form.submit t('global.forms.submit'), class: green_btn %>
  </div>
<% end %>

app/views/subscriptions/_questions.html.erb
<%= form_with model: survey, data: { controller: 'nested-form', nested_form_wrapper_selector_value: '.nested-form-wrapper' } do |f| %>

  <%= f.fields_for :survey_answers do |form| %>
        <div>
          <% if form.object.question.question_type == 'long_answer' %>
            <%= form.label form.object.question.question %>
            <%= form.text_field :answer %>
            <%= form.hidden_field :question_id, value: form.object.question.id %>
          <% else %>
            <%= form.label form.object.question.question %>
            <%= form.select :answer, form.object.question.alternatives, {} %>
            <%= form.hidden_field :question_id, value: form.object.question.id %>

          <% end %>
        </div>
      <% end %>

  <%= f.hidden_field :completed, value: true %>
  <%= f.submit 'Save' %>
<% end %>

app/views/surveys/_completed_survey.html.erb
<h2><%= t('survey.index.completed') %></h2>

app/views/surveys/_form.html.erb
<%= form_with url: surveys_path do |f| %>
  <%= f.hidden_field :subscription_id, value: subscription.id %>
  <%= f.hidden_field :category, value: category_name %>
  <%= f.submit t('survey.index.survey_redirection'), class: green_btn %>
<% end %>

app/views/surveys/_survey_link.html.erb
<div class="card text-center">
  <div class="card-header">
    <%= t 'survey.index.thanks' %>
  </div>
  <div class="card-body">
    <h5 class="card-title"><%= t 'survey.index.survey_coupon' %></h5>
    <%= render 'surveys/form', subscription: @subscription, category_name: 'coupon_subscription' %>
  </div>
</div>

app/views/surveys/show.html.erb
<div class="container">
  <div class="mb-3">
    <%= complete_subscription(@survey) %>
  </div>
  <%= render 'shared/redirect_home' %>
</div>